version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=a376de25ecf68323ea29a065292e7e8ef19b1a6363c8cb19c4e1971dd623c2f6
      - GENERIC_TIMEZONE=Asia/Singapore
      - TZ=Asia/Singapore
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_TUNNEL_URL=https://df9655c9ca86.ngrok-free.app
      - WEBHOOK_URL=https://df9655c9ca86.ngrok-free.app
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/n8n-database2.sqlite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Password1234
    volumes:
      - /Users/alysson/dev/db/sqlite-n8n-db:/home/node/.n8n
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/alysson/dev/db/redis-n8n-db:/data
    command: ["redis-server", "--requirepass", "Password1234"]
    restart: unless-stopped